/**
 * strategic-reports.ts — Server Actions
 *
 * Three public actions consumed by ReportsTab (client component):
 *   1. checkReportEligibility  — reads DB, no side effects
 *   2. generateStrategicReport — AI + Puppeteer, writes files + DB row
 *   3. getReportHistory        — reads DB, no side effects
 *
 * Auth pattern: uses getSession() from @/lib/auth (same as every other
 * action in this codebase) instead of Clerk's auth() which doesn't work
 * in the request context created by client-initiated server actions.
 */

'use server';

import { getSession } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { generateReportHTML } from '@/lib/ai-report-designer';
import { convertHtmlToPdf } from '@/lib/html-to-pdf';
import path from 'path';
import fs from 'fs/promises';

// How many reports a user may generate per calendar month
const MONTHLY_LIMIT = 5;

// Reports are served as static files from /public/reports/
const REPORTS_DIR = path.join(process.cwd(), 'public', 'reports');

// ---------------------------------------------------------------------------
// checkReportEligibility
// ---------------------------------------------------------------------------

/**
 * Returns the user's current eligibility to generate a report.
 * Called server-side on page load AND client-side after generation to refresh UI.
 *
 * Data completeness rules match what the AI report needs:
 *   - brandSummary present
 *   - ≥5 competitive matrix charts
 *   - ≥1 competitor in keyword intelligence
 *   - ≥1 client offering in products/services
 */
export async function checkReportEligibility(workspaceId: string) {
  const session = await getSession();
  if (!session) throw new Error('Unauthorized');
  const userId = session.userId;

  // Count reports generated by this user in the current calendar month
  const startOfMonth = new Date();
  startOfMonth.setDate(1);
  startOfMonth.setHours(0, 0, 0, 0);

  const reportsThisMonth = await prisma.strategicReport.count({
    where: { userId, reportDate: { gte: startOfMonth } },
  });

  const workspace = await prisma.workspace.findUnique({
    where: { id: workspaceId },
    select: {
      brandSummary: true,
      audienceInsights: true,
      competitors: { where: { userDecision: 'ACCEPTED' } },
    },
  });

  const insights = workspace?.audienceInsights as any;
  const missingData: string[] = [];

  if (!workspace?.brandSummary) missingData.push('Brand Memory');

  // DB key: competitiveMatrices.charts (array)
  if (!insights?.competitiveMatrices?.charts || insights.competitiveMatrices.charts.length < 5)
    missingData.push('Market Matrices (5 charts required)');

  // DB key: competitorKeywordsIntel.competitors (array)
  if (!insights?.competitorKeywordsIntel?.competitors?.length)
    missingData.push('Competitor Keywords');

  // DB key: productsServicesIntel.client_offerings.offerings (array)
  // Note: snake_case field names — the AI uses client_offerings not clientOfferings
  if (!insights?.productsServicesIntel?.client_offerings?.offerings?.length)
    missingData.push('Products & Services');

  return {
    canGenerate: reportsThisMonth < MONTHLY_LIMIT && missingData.length === 0,
    reportsThisMonth,
    remainingReports: MONTHLY_LIMIT - reportsThisMonth,
    missingData,
  };
}

// ---------------------------------------------------------------------------
// generateStrategicReport
// ---------------------------------------------------------------------------

/**
 * Full report generation pipeline:
 *   1. Eligibility gate
 *   2. Fetch workspace data
 *   3. Call Gemini (OpenAI fallback) → styled HTML
 *   4. Save HTML to disk (editable / debug copy)
 *   5. Puppeteer → PDF
 *   6. Persist StrategicReport row in DB
 *   7. Return public URLs for download
 *
 * Expect ~30-60 s execution time (AI call + Chromium startup).
 */
export async function generateStrategicReport(workspaceId: string) {
  const session = await getSession();
  if (!session) throw new Error('Unauthorized');
  const userId = session.userId;

  // Gate: check eligibility before doing any expensive work
  const eligibility = await checkReportEligibility(workspaceId);
  if (!eligibility.canGenerate) {
    throw new Error(
      eligibility.missingData.length > 0
        ? `Missing data: ${eligibility.missingData.join(', ')}`
        : 'Monthly report limit reached',
    );
  }

  // Fetch the full workspace including accepted competitors
  const workspace = await prisma.workspace.findUnique({
    where: { id: workspaceId },
    include: { competitors: { where: { userDecision: 'ACCEPTED' } } },
  });
  if (!workspace) throw new Error('Workspace not found');

  const insights = workspace.audienceInsights as any;
  const brandSummary = workspace.brandSummary as any;

  // Ensure the public output directory exists
  await fs.mkdir(REPORTS_DIR, { recursive: true });

  // Unique filename per generation run
  const timestamp = Date.now();
  const baseFilename = `strategic-report-${workspaceId}-${timestamp}`;
  const htmlPath = path.join(REPORTS_DIR, `${baseFilename}.html`);
  const pdfPath = path.join(REPORTS_DIR, `${baseFilename}.pdf`);

  // Step 1 — AI designs the report as HTML
  console.log('[strategic-reports] Generating HTML with AI...');
  const reportHTML = await generateReportHTML({
    companyName: brandSummary?.businessName || workspace.name || 'Your Company',
    websiteUrl: workspace.websiteUrl,
    reportDate: new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
    brandSummary,
    competitors: workspace.competitors,
    matrices: insights?.competitiveMatrices ?? null,
    keywords: insights?.competitorKeywordsIntel ?? null,
    offerings: insights?.productsServicesIntel ?? null,
  });

  // Step 2 — Persist HTML (useful for debugging and as an "editable" copy)
  await fs.writeFile(htmlPath, reportHTML, 'utf-8');

  // Step 3 — Convert to PDF via Puppeteer
  console.log('[strategic-reports] Converting to PDF with Puppeteer...');
  await convertHtmlToPdf(reportHTML, pdfPath);

  // Step 4 — Record the generated report in the database
  const pdfStats = await fs.stat(pdfPath);

  await prisma.strategicReport.create({
    data: {
      workspaceId,
      userId,
      // "docxPath" field repurposed for the HTML version (editable copy)
      docxPath: `/reports/${baseFilename}.html`,
      pdfPath: `/reports/${baseFilename}.pdf`,
      fileSize: pdfStats.size,
      sectionsIncluded: [
        'Executive Summary',
        'Brand Profile',
        'Competitive Landscape',
        'Market Positioning Matrices',
        'Keyword Intelligence',
        'Products & Services',
        'Strategic Recommendations',
      ],
      competitorsCount: workspace.competitors.length,
      keywordsAnalyzed: insights?.competitorKeywordsIntel?.competitors?.length ?? 0,
      chartsGenerated: insights?.competitiveMatrices?.charts?.length ?? 0,
    },
  });

  console.log('[strategic-reports] Report saved successfully.');

  return {
    success: true,
    // "DOCX" button in UI will now open the HTML version
    docxUrl: `/reports/${baseFilename}.html`,
    pdfUrl: `/reports/${baseFilename}.pdf`,
    fileSize: pdfStats.size,
  };
}

// ---------------------------------------------------------------------------
// getReportHistory
// ---------------------------------------------------------------------------

/**
 * Returns the 20 most recent reports for this workspace, newest first.
 * Used both server-side (initial page load) and client-side (post-generation refresh).
 */
export async function getReportHistory(workspaceId: string) {
  const session = await getSession();
  if (!session) throw new Error('Unauthorized');

  return prisma.strategicReport.findMany({
    where: { workspaceId },
    orderBy: { reportDate: 'desc' },
    take: 20,
  });
}
