/**
 * strategic-reports.ts — Server Actions
 *
 * Three public actions consumed by ReportsTab (client component):
 *   1. checkReportEligibility  — reads DB, no side effects
 *   2. generateStrategicReport — AI + Puppeteer, writes files + DB row
 *   3. getReportHistory        — reads DB, no side effects
 *
 * Auth pattern: uses getSession() from @/lib/auth (same as every other
 * action in this codebase) instead of Clerk's auth() which doesn't work
 * in the request context created by client-initiated server actions.
 *
 * All three took a workspaceId straight from the client and never checked
 * that the caller owns it, so any signed-in user could generate and read
 * another tenant's report — brand memory, competitors and positioning
 * matrices, in one PDF. Every entry point now goes through
 * every entry point now carries userId inside the workspace query itself.
 */

'use server';

import { getSession } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { generateReportHTML } from '@/lib/ai-report-designer';
import { convertHtmlToPdf } from '@/lib/html-to-pdf';
import path from 'path';
import { tmpdir } from 'os';
import fs from 'fs/promises';
import { asContentLanguage } from '@/lib/content-language';
import { missingReportRequirements } from '@/lib/report-readiness';
import { reportReference } from '@/lib/report/format';
import { REPORT_LIST_SELECT } from '@/lib/report/list';

// How many reports a user may generate per calendar month
const MONTHLY_LIMIT = 5;

/*
  Reports used to be written into `public/`, which Next serves as static files
  with no authentication: anyone holding the URL could read another account's
  whole strategy report, and the workspace id was right there in the filename.
  They also vanished on every redeploy, because the container filesystem is
  ephemeral.

  The bytes now live on the row and are served by /api/reports/[id], which
  checks the session and the owner. Puppeteer still needs somewhere to write a
  file, so it gets a scratch directory that nothing serves.
*/
const SCRATCH_DIR = path.join(tmpdir(), 'contivo-reports');

// A missing workspace and someone else's workspace return the same message,
// so neither can be used to test which workspace ids exist.
const NOT_FOUND = 'Workspace not found';

// ---------------------------------------------------------------------------
// checkReportEligibility
// ---------------------------------------------------------------------------

/**
 * Returns the user's current eligibility to generate a report.
 * Called server-side on page load AND client-side after generation to refresh UI.
 *
 * Data completeness rules match what the AI report needs:
 *   - brandSummary present
 *   - ≥5 competitive matrix charts
 *   - ≥1 competitor in keyword intelligence
 *   - ≥1 client offering in products/services
 */
export async function checkReportEligibility(workspaceId: string) {
  const session = await getSession();
  if (!session) throw new Error('Unauthorized');
  const userId = session.userId;

  // Count reports generated by this user in the current calendar month
  const startOfMonth = new Date();
  startOfMonth.setDate(1);
  startOfMonth.setHours(0, 0, 0, 0);

  const reportsThisMonth = await prisma.strategicReport.count({
    where: { userId, reportDate: { gte: startOfMonth } },
  });

  // findFirst, not findUnique: the userId filter belongs in the query, so a
  // later reader of this row cannot skip the ownership check by accident.
  const workspace = await prisma.workspace.findFirst({
    where: { id: workspaceId, userId },
    select: {
      brandSummary: true,
      audienceInsights: true,
      competitors: { where: { userDecision: 'ACCEPTED' } },
    },
  });
  if (!workspace) throw new Error(NOT_FOUND);

  const insights = workspace.audienceInsights as any;
  const missingData = missingReportRequirements(workspace.brandSummary, insights);

  return {
    canGenerate: reportsThisMonth < MONTHLY_LIMIT && missingData.length === 0,
    reportsThisMonth,
    remainingReports: MONTHLY_LIMIT - reportsThisMonth,
    missingData,
  };
}

// ---------------------------------------------------------------------------
// generateStrategicReport
// ---------------------------------------------------------------------------

/**
 * Full report generation pipeline:
 *   1. Eligibility gate
 *   2. Fetch workspace data
 *   3. Call Gemini (OpenAI fallback) → styled HTML
 *   4. Save HTML to disk (editable / debug copy)
 *   5. Puppeteer → PDF
 *   6. Persist StrategicReport row in DB
 *   7. Return public URLs for download
 *
 * Expect ~30-60 s execution time (AI call + Chromium startup).
 */
export async function generateStrategicReport(workspaceId: string) {
  const session = await getSession();
  if (!session) throw new Error('Unauthorized');
  const userId = session.userId;

  // Gate: check eligibility before doing any expensive work
  const eligibility = await checkReportEligibility(workspaceId);
  if (!eligibility.canGenerate) {
    throw new Error(
      eligibility.missingData.length > 0
        ? `Missing data: ${eligibility.missingData.join(', ')}`
        : 'Monthly report limit reached',
    );
  }

  // Fetch the full workspace including accepted competitors
  const workspace = await prisma.workspace.findFirst({
    where: { id: workspaceId, userId },
    include: { competitors: { where: { userDecision: 'ACCEPTED' } } },
  });
  if (!workspace) throw new Error(NOT_FOUND);

  const insights = workspace.audienceInsights as any;
  const brandSummary = workspace.brandSummary as any;

  await fs.mkdir(SCRATCH_DIR, { recursive: true });

  // Unique filename per generation run
  const timestamp = Date.now();
  const baseFilename = `strategic-report-${workspaceId}-${timestamp}`;
  const htmlPath = path.join(SCRATCH_DIR, `${baseFilename}.html`);
  const pdfPath = path.join(SCRATCH_DIR, `${baseFilename}.pdf`);

  // Step 1 — render the report: our template, the model's prose.
  // The date is formatted inside the template, from `generatedAt` and the
  // workspace's own language. Formatting it here with a hardcoded 'en-US'
  // was how Persian reports ended up carrying an English date in Latin digits.
  console.log('[strategic-reports] Rendering report...');
  const generatedAt = new Date(timestamp);
  const reportHTML = await generateReportHTML({
    companyName: brandSummary?.businessName || workspace.name || 'Your Company',
    websiteUrl: workspace.websiteUrl,
    // The DB row does not exist yet, so the run's timestamp identifies it. It
    // is unique per generation and, unlike the row's cuid, safe to print.
    reportId: String(timestamp),
    generatedAt,
    brandSummary,
    competitors: workspace.competitors,
    matrices: insights?.competitiveMatrices ?? null,
    keywords: insights?.competitorKeywordsIntel ?? null,
    offerings: insights?.productsServicesIntel ?? null,
    language: asContentLanguage(workspace.contentLanguage),
  });

  // Step 2 — Persist HTML (useful for debugging and as an "editable" copy)
  await fs.writeFile(htmlPath, reportHTML, 'utf-8');

  // Step 3 — Convert to PDF via Puppeteer
  console.log('[strategic-reports] Converting to PDF with Puppeteer...');
  await convertHtmlToPdf(reportHTML, pdfPath, asContentLanguage(workspace.contentLanguage), {
    brand: 'Contivo · contivo.app',
    reference: reportReference(String(timestamp), generatedAt),
  });

  // Step 4 — Record the report, bytes and all, then delete the scratch files.
  const pdfBytes = await fs.readFile(pdfPath);
  await fs.rm(htmlPath, { force: true });
  await fs.rm(pdfPath, { force: true });

  const report = await prisma.strategicReport.create({
    data: {
      workspaceId,
      userId,
      // Filled in below, once the row has an id to address it by. These two
      // columns still hold a URL because the history list renders them
      // directly; on rows from before this change it is a /reports path that
      // no longer resolves.
      docxPath: '',
      pdfPath: '',
      pdfData: pdfBytes,
      htmlData: Buffer.from(reportHTML, 'utf-8'),
      fileSize: pdfBytes.byteLength,
      sectionsIncluded: [
        'Executive Summary',
        'Brand Profile',
        'Competitive Landscape',
        'Market Positioning Matrices',
        'Keyword Intelligence',
        'Products & Services',
        'Strategic Recommendations',
      ],
      competitorsCount: workspace.competitors.length,
      keywordsAnalyzed: insights?.competitorKeywordsIntel?.competitors?.length ?? 0,
      chartsGenerated: insights?.competitiveMatrices?.charts?.length ?? 0,
    },
  });

  const pdfUrl = `/api/reports/${report.id}`;
  const docxUrl = `/api/reports/${report.id}?format=html`;
  await prisma.strategicReport.update({
    where: { id: report.id },
    data: { pdfPath: pdfUrl, docxPath: docxUrl },
  });

  console.log('[strategic-reports] Report saved successfully.');

  return {
    success: true,
    // The "DOCX" button opens the HTML version.
    docxUrl,
    pdfUrl,
    fileSize: pdfBytes.byteLength,
  };
}

// ---------------------------------------------------------------------------
// getReportHistory
// ---------------------------------------------------------------------------

/**
 * Returns the 20 most recent reports for this workspace, newest first.
 * Used both server-side (initial page load) and client-side (post-generation refresh).
 */
export async function getReportHistory(workspaceId: string) {
  const session = await getSession();
  if (!session) throw new Error('Unauthorized');

  // Report rows carry public file URLs, so the listing is gated too.
  const owned = await prisma.workspace.findFirst({
    where: { id: workspaceId, userId: session.userId as string },
    select: { id: true },
  });
  if (!owned) throw new Error(NOT_FOUND);

  return prisma.strategicReport.findMany({
    where: { workspaceId },
    orderBy: { reportDate: 'desc' },
    take: 20,
    select: REPORT_LIST_SELECT,
  });
}
